openapi: 3.0.3
info:
  title: 天気アプリのBFF仕様書
  description: |-
    kadai-2-weather-app-KawamuraTaisei と kadai-2-weather-api-KawamuraTaiseiで使われる\
    岩手県内陸の今日、明日の天気をテキスト形式で表示する
  version: 0.0.1
  contact: {}
servers:
  - url: https://localhost:3000/
tags:
  - name: api
    description: Everything about Weater
paths:
  /v0.2/api:
    get:
      tags:
        - api
      summary: Find Weather
      description: prefとareaに対応する今日と明日の天気を返す
      operationId: /api
      parameters:
        - name: pref
          in: query
          description: 都道府県
          required: true
          schema:
            type: string
        - name: area
          in: query
          description: 市区町村
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/ApiResponse'
        '400':
          description: Invalid ID supplied
        '404':
          description: Not found
components:
  schemas:
    Area:
      required:
        - pref
        - area
      type: object
      properties:
        pref:
          type: string
          example: 岩手県
        area:
          type: string
          example: 内陸
    ApiResponse:
      type: object
      properties:
        pref:
          type: string
          example: 岩手県
        area:
          type: string
          example: 内陸
        today:
          type: object
          properties:
            todaySky:
              type: string
              example: くもり 時々 雨
            tempHigh:
              type: string
              example: 27.0
            tempLow:
              type: string
              example: 16.4
          description: The weather on today
        tomorrow:
          type: object
          properties:
            sky:
              type: string
              example: 晴れ
            tempHigh:
              type: string
              example: 25
            tempLow:
              type: string
              example: 17
          description: The weather on tomorrow
  requestBodies:
    Area:
      description: Area Object
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Area'
